name: proto_data_analyzer
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  protobuf:
  protobuf_wellknown:
  belatuk_symbol_table: ^2.0.0
dev_dependencies:
  test:
  very_good_analysis: ^5.1.0
